///////////// MOVIE LIBRARY GET MOVIE
export const GET_MOVIE_LIBRARY_START = 'GET_MOVIE_LIBRARY_START';
export const GET_MOVIE_LIBRARY = 'GET_MOVIE_LIBRARY';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const MOVIE_NOT_FOUND = 'MOVIE_NOT_FOUND';